adding the workflow to check the format using CFN Lint
f5devcentral/aws-waf-solution-template pull request #13
Opened 2021-09-17 08:12 UTC by sshajiya

CFN Lint format check Added for CFTemplate

2021-09-20 19:12 UTC, 464d41 requested changes

2021-09-20 19:12 UTC, 464d41 commented on .github/workflows/pipeline.yml
> +        uses: scottbrenner/cfn-lint-action@v2
It is important to statically define linter version. Please install a latest version explicitly with pip.

2021-09-23 06:47 UTC, sshajiya commented
Incorporated the comments

2021-09-24 02:43 UTC, 464d41 requested changes

2021-09-24 02:43 UTC, 464d41 commented on .github/workflows/release_initial_repo.yml
> -name: Release Initial Repo
This workflow uploads initial git repo to S3. Do not delete this workflow.

2021-09-27 19:57 UTC, merged