adding the required files for static page verification of CFT
f5devcentral/aws-waf-solution-template pull request #25
Opened 2021-11-11 17:12 UTC by sshajiya

2021-11-15 23:50 UTC, 464d41 requested changes

2021-11-15 23:50 UTC, 464d41 commented on .github/workflows/static_page_verification.yml
> +          name: ${{secrets.STACK_NAME}}
Stack name is not a secret. Why you don't hardcode some prefix?

2021-11-15 23:50 UTC, 464d41 commented on .github/workflows/static_page_verification.yml
> +name: Cloud Formation Template Static Page verification
Change destination branch from master to dev. Make sure your code works with latest template from dev branch.

2021-11-15 23:50 UTC, 464d41 commented on .github/workflows/static_page_verification.yml
> +          pwd
Debug messages should not to to the final workflow.

2021-11-15 23:50 UTC, 464d41 commented on .github/workflows/static_page_verification.yml
> +          git config --global user.email ${{secrets.USER_NAME}}
Can username be just a random string? If so just hardcode.

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/appspec.yml
> +version: 0.0
Can you place all workflow related files to ".github/workflows" folder?

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/delete_stack.py
> +import boto3
Please use "aws-actions" to delete the stack.

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/index.html
> +<html>
Similar to appspec.yaml. Would be good if all workflow related files move to ".github/workflow" folder.

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/utils.py
> +import boto3
Would be good if all workflow related files move to ".github/workflow" folder.

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/verify_cft_nap.py.py
> +import boto3
Would be good if all workflow related files move to ".github/workflow" folder.

2021-11-15 23:50 UTC, 464d41 commented on scripts/pipeline/verify_cft_nap.py.py
> +import os
Remove extra ".py" from file extension.

2021-11-18 23:39 UTC, 464d41 commented
Why did u removed appspec.yaml and index.html files from the PR? They still seem to be required.

2021-11-18 23:40 UTC, 464d41 commented
Please give a link to this workflow results with latest template in dev branch.

2021-11-24 06:42 UTC, sshajiya commented
> 

https://github.com/sshajiya/aws-waf-solution-template/runs/4308204639?check_suite_focus=true

2021-11-24 07:20 UTC, sshajiya commented
> Please give a link to this workflow results with latest template in dev branch.
https://github.com/sshajiya/aws-waf-solution-template/runs/4308204639?check_suite_focus=true
The above link is the passed workflow log with the existed template in master branch.

With the new template in dev branch is it failing with default parameter values and asking the new sshkey for the ec2 instance.
Here is the link of log result for reference.

https://github.com/sshajiya/aws-waf-solution-template/runs/4308853375?check_suite_focus=true

2021-11-30 06:33 UTC, 464d41 commented
> With the new template in dev branch is it failing with default parameter values and asking the new sshkey for the ec2 instance.

In order to merge your test into master it has to run successfully with latest template version from dev branch. Please make it work and update PR accordingly.

2021-12-07 15:50 UTC, closed without merging